import { Injectable } from '@nestjs/common';

export interface ObsidianNote {
  title: string;
  tags: string[];
  contentMarkdown: string;
  createdAt: string;
}

@Injectable()
export class ObsidianService {
  generateObsidianMarkdownNote(title: string, tags: string[], body: string): ObsidianNote {
    const frontmatter = `---
title: "${title}"
date: ${new Date().toISOString().split('T')[0]}
tags: [${tags.map((t) => `"${t}"`).join(', ')}]
type: financial-journal
system: SAKU-Financial-OS
---

# ${title}

${body}

---
*Generated by SAKU Obsidian Vault Bridge*
`;

    return {
      title,
      tags,
      contentMarkdown: frontmatter,
      createdAt: new Date().toISOString(),
    };
  }
}
